/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module priority_encoder_4to2(I, Y);
  input [3:0] I;
  wire [3:0] I;
  output [1:0] Y;
  wire [1:0] Y;
  wire [1:0] _0_;
  wire [1:0] _1_;
  wire [1:0] _2_;
  \$_MUX_  _3_ (
    .A(1'hx),
    .B(1'h0),
    .S(I[0]),
    .Y(_2_[0])
  );
  \$_MUX_  _4_ (
    .A(_2_[0]),
    .B(1'h1),
    .S(I[1]),
    .Y(_1_[0])
  );
  \$_MUX_  _5_ (
    .A(_2_[0]),
    .B(1'h0),
    .S(I[1]),
    .Y(_1_[1])
  );
  \$_MUX_  _6_ (
    .A(_1_[0]),
    .B(1'h0),
    .S(I[2]),
    .Y(_0_[0])
  );
  \$_MUX_  _7_ (
    .A(_1_[1]),
    .B(1'h1),
    .S(I[2]),
    .Y(_0_[1])
  );
  \$_MUX_  _8_ (
    .A(_0_[0]),
    .B(1'h1),
    .S(I[3]),
    .Y(Y[0])
  );
  \$_MUX_  _9_ (
    .A(_0_[1]),
    .B(1'h1),
    .S(I[3]),
    .Y(Y[1])
  );
  assign _2_[1] = _2_[0];
endmodule
